application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /logArena
  script: hearthstone.application
- url: /.*
  script: helloworld.application

libraries:
- name: webapp2
  version: latest
